apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: task.events        # <-- must match EXACTLY
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000    # 7 days, just an example
