apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "task-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "task-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "task-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: task-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:5432/{{ .Values.postgres.db }}"
            - name: DB_USER
              value: "{{ .Values.postgres.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: KAFKA_BOOTSTRAP
              value: "{{ .Values.kafka.bootstrapServers }}"
            - name: APICURIO_REGISTRY
              value: "{{ .Values.apicurio.registryUrl }}"
            - name: OIDC_ISSUER
              value: "{{ .Values.oidc.issuerUri }}"
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources: {{ toYaml .Values.resources | nindent 12 }}
